# Generated by Django 3.2.5 on 2021-07-01 23:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=30)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('bio', models.TextField(blank=True)),
                ('role', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Author'), (2, 'Webfairy'), (3, 'Contributor')], null=True)),
                ('photo', models.ImageField(blank=True, upload_to='users/%Y/%m/%d/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250, unique_for_date='publish')),
                ('author_pic', models.FileField(blank=True, default='blog/img/pic_filler.jpg', null=True, upload_to='blog/img')),
                ('category', models.CharField(choices=[('Branding', 'Branding'), ('Design', 'Design'), ('Tech', 'Tech'), ('Development', 'Development'), ('Marketing', 'Marketing')], default='Tech', max_length=25)),
                ('abstract_title', models.CharField(blank=True, default=None, max_length=250)),
                ('abstract', models.TextField(blank=True, null=True)),
                ('subheading_one', models.CharField(blank=True, default=None, max_length=250)),
                ('body', models.TextField(blank=True, null=True)),
                ('body_b', models.TextField(blank=True, null=True)),
                ('body_c', models.TextField(blank=True, null=True)),
                ('subheading_two', models.CharField(blank=True, default=None, max_length=250)),
                ('body_two', models.TextField(blank=True, null=True)),
                ('blog_img', models.FileField(blank=True, null=True, upload_to='blog/img')),
                ('blog_img_larger', models.FileField(blank=True, null=True, upload_to='blog/img')),
                ('img_caption_long', models.TextField(blank=True, null=True)),
                ('img_caption_short', models.CharField(blank=True, default=None, max_length=250)),
                ('quote', models.TextField(blank=True, null=True)),
                ('quote_author', models.CharField(blank=True, default=None, max_length=250)),
                ('code', models.TextField(blank=True, null=True)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'ordering': ('-publish',),
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('body', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=False)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.post')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
