# Generated by Django 3.2.5 on 2021-12-21 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='host',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='path',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
    ]
