# Generated by Django 3.2.5 on 2021-12-21 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_tracker', '0002_auto_20211221_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='object_id',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
    ]
