# Generated by Django 3.2.5 on 2021-12-21 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_tracker', '0003_alter_event_object_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='object_id',
            field=models.PositiveIntegerField(),
        ),
    ]
