# Generated by Django 3.2.5 on 2021-12-21 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_tracker', '0004_alter_event_object_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='object_id',
        ),
    ]
