# Generated by Django 3.2.5 on 2021-12-21 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_tracker', '0005_remove_event_object_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='object_id',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
    ]
